//#### BONUS ####

11. Write a function called 'convertArrayToAnObject' that turns an array (with an even number of elements) into a hash, by
pairing up elements. e.g. ['a', 'b', 'c', 'd'] becomes
{'a' => 'b', 'c' => 'd'}

function convertArrayToAnObject(array, keyValueMap) {
	var obj = {};
	var len = array.length;
	// Your function will be called for each item in the array.
	for (var i = 0; i < len; i++) {
		var curVal = array[i];
		// Just like with [].forEach(), your function will be passed the
		// curent item of the array, its index, and the array it's in.
		var keyValuePair = keyValueMap(curVal, i, array);
		// Your function should return a 2-value array with the key
		// and value for a new property in the object to be returned.
		obj[keyValuePair[0]] = keyValuePair[1];
	}
	return obj;
}


}

// 12. Write a function called 'fizzBuzz' that takes any number and returns a value based on these rules

// But for multiples of three print "Fizz" instead of the number
// For the multiples of five print "Buzz".
// For numbers which are multiples of both three and five print "FizzBuzz".

function fizzBuzz(value) {

  switch (true) {
  case value % 3 == 0 && value % 5 == 0:
  return "FizzBuzz";
  break;
  case value % 5 == 0 && value % 3 != 0:
  return "Buzz";
  break;
  case value % 3 == 0 && value % 5 != 0:
  return "Fizz";
  break;
  }
}

console.log(fizzBuzz(6));

// Project Euler Task
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//
// Find the sum of all the multiples of 3 or 5 below 1000.


var sum = 0;
for (var i = 0 ; i < 1000 ; i++)
{
   if ( i % 3 === 0 || i % 5 ===0)
   {
     sum += i;
   }
} console.log(sum);

//  233168

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var Num1 = 1;
var Num2 = 2;
var sum = 0;

do {
  sum = Num1 + Num2;
  Num1 = Num2;
  Num2 = sum;

  if (Num2 % 2 === 0)
    sum = sum + Num2;

  }
  while (Num2 < 4000000);

console.log(sum);

//5702887
